services:
  productservice:
    build: 
      context: .
      dockerfile: ProductService.Api/dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbConnection=${DB_CONNECTION}
    depends_on:
      - postgredb 

  postgredb:
    image: postgres:15-alpine
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DATABASE_NAME}
    volumes:
      - pspgdata:/var/lib/postgresql/data

volumes:
  pspgdata: