# Image
FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine  AS build

WORKDIR /src

COPY ["./ProductService.Api/ProductService.Api.csproj", "ProductService.Api/"]
COPY ["./ProductService.Application/ProductService.Application.csproj", "ProductService.Application/"]
COPY ["./ProductService.Infrastructure/ProductService.Infrastructure.csproj", "ProductService.Infrastructure/"]
COPY ["./ProductService.Domain/ProductService.Domain.csproj", "ProductService.Domain/"]

RUN dotnet restore "./ProductService.Api/ProductService.Api.csproj"
COPY . .

RUN dotnet publish "./ProductService.Api/ProductService.Api.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0-alpine
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

COPY --from=build /app/publish .

ENTRYPOINT [ "dotnet", "ProductService.Api.dll" ]